import threading
from typing import Any

rds_default_state = {
    "running": False,
    "rds_level": 2.0,
    "pi": "82FF",
    "pty": 20,
    "tp": 0,
    "ta": 0,
    "ms": 1,
    "di_stereo": 1,
    "di_head": 0,
    "di_comp": 1,
    "di_dyn": 0,
    "en_af": 0,
    "af_list": "88.1, 98.8, 106.6",
    "af_method": "A",
    "ps_dynamic": "3s:Stereo- 3s:Fool 3s:Open 3s:Source 3s:Stereo 3s:and 3s:RDS 2s:Coder",
    "ps_centered": True,
    "rt_text": "10s:StereoFool Stereo and RDS Coder/10s:100% Python, Multi-Platform, Web-based",
    "rt_manual_buffers": False,
    "rt_cycle_ab": False,
    "rt_a": "StereoFool: MPX + RDS + UI",
    "rt_b": "StereoFool: Mono MPX + RDS",
    "rt_cr": True,
    "rt_centered": False,
    "rt_mode": "2A",
    "rt_cycle": True,
    "rt_cycle_time": 5,
    "rt_active_buffer": 0,
    "rt_ab_cycle_count": 2,
    "rt_plus_format_a": "{artist} - {title}",
    "rt_plus_format_b": "{artist} - {title}",
    "en_rt_plus": False,
    "ecc": "E3",
    "lic": "1D",
    "tz_offset": 1.0,
    "en_ct": 1,
    "en_id": 1,
    "ps_long_32": "StereoFool Stereo and RDS Coder",
    "en_lps": 1,
    "lps_centered": False,
    "lps_cr": True,
    "ptyn": "-STEREO-",
    "en_ptyn": 1,
    "ptyn_centered": False,
    "auto_start": True,
    "rds_freq": 57000,
    "rds_gaussian_enabled": True,
    "rds_gaussian_bw_hz": 2400.0,
    "rds_gaussian_taps": 81,
    "group_sequence": "0A 0A 2A 0A",
    "scheduler_auto": True,
    "scheduler_standard": True,
    "scheduler_standard_lps": True,
}

rds_state: dict[str, Any] = rds_default_state.copy()
resolved_cache: dict[str, str] = {
    "ps_dynamic": "",
    "ps_long_32": "",
    "rt_text": "",
    "rt_a": "",
    "rt_b": "",
    "ptyn": "",
}
monitor_data: dict[str, Any] = {
    "ps": "OFF AIR",
    "rt": "",
    "lps": "",
    "ptyn": "",
    "af": "",
    "pi": "0000",
    "pty_idx": 10,
    "rt_plus_info": "",
    "heartbeat": 0,
    "pilot_generated": True,
    "sample_rate": 0,
    "device_out_name": "",
    "device_in_name": "",
}

mpx_state: dict[str, Any] = {
    "running": False,
    "device_out_idx": 0,
    "device_in_idx": -1,
    "pilot_level": 0.1,
    "sum_level": 0.9,
    "diff_level": 0.9,
    "test_tone_freq": 1000.0,
    "source_mode": "input",
    "mono_mode": False,
    "test_tone_mode": "mono",
    "hpf_hz": 30.0,
    "hf_trim_db": 0.0,
    "hf_trim_hz": 4000.0,
    "processing_rate_hz": 0,
    "processing_bypass": False,
    "multiband_enabled": False,
    "multiband_low_threshold_db": 0.0,
    "multiband_mid_threshold_db": 0.0,
    "multiband_high_threshold_db": 0.0,
    "multiband_low_ratio": 3.0,
    "multiband_mid_ratio": 3.0,
    "multiband_high_ratio": 3.0,
    "multiband_low_attack_ms": 50.0,
    "multiband_mid_attack_ms": 50.0,
    "multiband_high_attack_ms": 50.0,
    "multiband_low_release_ms": 250.0,
    "multiband_mid_release_ms": 250.0,
    "multiband_high_release_ms": 250.0,
    "multiband_low_hz": 400.0,
    "multiband_high_hz": 2000.0,
    "stereo_widen_enabled": False,
    "stereo_widen_width": 0.5,
    "stereo_widen_center": 0.5,
    "stereo_widen_mix": 1.0,
    "preemphasis_limit_enabled": False,
    "preemphasis_limit_threshold": 0.95,
    "composite_clip_enabled": False,
    "composite_clip_threshold": 0.98,
    "input_gain_db": 0.0,
    "limit_mpx": False,
    "limit_threshold": 0.98,
    "limit_lookahead_ms": 5.0,
    "limit_lookahead_enabled": True,
    "mpx_dc_block_enabled": True,
    "mpx_dc_block_hz": 2.0,
    "mpx_notch_enabled": False,
    "mpx_notch_freq_hz": 19000.0,
    "mpx_notch_q": 12.0,
    "wav_record_enabled": False,
    "wav_record_path": "mpx_capture.wav",
    "output_gain_db": 0.0,
    "output_enabled": True,
    "preemphasis_us": 50,
    "mpx_deviation_khz": 75.0,
    "en_rds": True,
    "monitor_enabled": False,
    "monitor_device_idx": -1,
    "monitor_rate_hz": 48000,
}

meter_state: dict[str, float] = {
    "input_rms": 0.0,
    "input_peak": 0.0,
    "input_vu": 0.0,
    "input_rms_l": 0.0,
    "input_rms_r": 0.0,
    "input_vu_l": 0.0,
    "input_vu_r": 0.0,
    "input_pre_rms": 0.0,
    "input_pre_peak": 0.0,
    "input_pre_vu": 0.0,
    "mpx_rms": 0.0,
    "mpx_peak": 0.0,
    "mpx_vu": 0.0,
    "output_rms": 0.0,
    "output_peak": 0.0,
    "output_vu": 0.0,
    "limiter_active": False,
    "multiband_enabled": False,
    "multiband_active": False,
    "preemph_limit_enabled": False,
    "preemph_limit_active": False,
    "composite_clip_enabled": False,
    "composite_clip_active": False,
}

meter_lock = threading.Lock()

wave_state: dict[str, list[float]] = {"input_wave": [], "mpx_wave": []}
wave_lock = threading.Lock()

dsp_control: dict[str, bool] = {"reset": False}
